import './index.css';
import { Urbanist } from 'next/font/google';
import ToastProvider from '../providers/toast-provder';

const font = Urbanist({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={font.className}>
                <ToastProvider />
                {children}
            </body>
        </html>
    );
}
